pull-request.yml updated

diff --git a/.github/workflows/pull-request.yml b/.github/workflows/pull-request.yml
--- a/.github/workflows/pull-request.yml
+++ b/.github/workflows/pull-request.yml
@@ -417,7 +417,38 @@ jobs:
           docker stop talawa-admin-app-container
           docker rm talawa-admin-app-container
    
+  generate-docs:
+    runs-on: ubuntu-latest
+    permissions:
+        contents: write
+ 
+    steps:
+      - name: Checkout the Repository
+        uses: actions/checkout@v4
+        with:
+          fetch-depth: 0
+          token: ${{ secrets.GITHUB_TOKEN }}
 
+      - name: Generate Documentation
+        run: npm run generate-docs
+
+      - name: Commit and Push Changes
+        env:
+          HEAD_REF: ${{ github.head_ref }}
+        run: |
+          if [[ $(git status --porcelain) ]]; then
+            echo "Changes detected. Auto-committing updates."
+            git config user.name "gautam-divyanshu"
+            git config user.email "137816099+gautam-divyanshu@users.noreply.github.com"
+            git add --all
+            git commit -m "Auto-generate documentation"
+            if ! git push origin HEAD:"$HEAD_REF"; then
+              echo "Failed to push changes. Please check if you have the correct permissions."
+              exit 1
+            fi
+          else
+            echo "No changes detected."
+          fi
   Test-Docusaurus-Deployment:
     name: Test Deployment to https://docs-admin.talawa.io
     runs-on: ubuntu-latest
