Merge from develop (#3243)
* 20250110082558 Deleted all files in the main branch in anticipation of merging develop into main cleanly

* 20250110082559 Merge develop into main

diff --git a/.github/workflows/pull-request.yml b/.github/workflows/pull-request.yml
--- a/.github/workflows/pull-request.yml
+++ b/.github/workflows/pull-request.yml
@@ -37,19 +37,19 @@ jobs:
 
       - name: Count number of lines
         run: |
-          chmod +x ./.github/workflows/countline.py
-          ./.github/workflows/countline.py --lines 600 --exclude_files src/screens/LoginPage/LoginPage.tsx src/GraphQl/Queries/Queries.ts src/screens/OrgList/OrgList.tsx src/GraphQl/Mutations/mutations.ts src/components/EventListCard/EventListCardModals.tsx src/components/TagActions/TagActionsMocks.ts src/utils/interfaces.ts src/screens/MemberDetail/MemberDetail.tsx
+          chmod +x ./.github/workflows/scripts/countline.py
+          ./.github/workflows/scripts/countline.py --lines 600 --exclude_files src/screens/LoginPage/LoginPage.tsx src/GraphQl/Queries/Queries.ts src/screens/OrgList/OrgList.tsx src/GraphQl/Mutations/mutations.ts src/components/EventListCard/EventListCardModals.tsx src/components/TagActions/TagActionsMocks.ts src/utils/interfaces.ts src/screens/MemberDetail/MemberDetail.tsx
 
       - name: Get changed TypeScript files
         id: changed-files
-        uses: tj-actions/changed-files@v40
+        uses: tj-actions/changed-files@v45
       - name: Check formatting
         if: steps.changed-files.outputs.only_changed != 'true'
         run: npm run format:check
         
       - name: Run formatting if check fails
         if: failure()
-        run: npm run format
+        run: npm run format:fix
 
       - name: Check for type errors
         if: steps.changed-files.outputs.only_changed != 'true'
@@ -58,8 +58,8 @@ jobs:
       - name: Check for linting errors in modified files
         if: steps.changed-files.outputs.only_changed != 'true'
         env: 
-          CHANGED_FILES: ${{ steps.changed_files.outputs.all_changed_files }}
-        run: npx eslint ${CHANGED_FILES} && python .github/workflows/eslint_disable_check.py
+          CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
+        run: npx eslint ${CHANGED_FILES}
         
       - name: Check for TSDoc comments
         run: npm run check-tsdoc # Run the TSDoc check script
@@ -71,8 +71,8 @@ jobs:
 
       - name: Compare translation files
         run: |
-          chmod +x .github/workflows/compare_translations.py
-          python .github/workflows/compare_translations.py --directory public/locales
+          chmod +x .github/workflows/scripts/compare_translations.py
+          python .github/workflows/scripts/compare_translations.py --directory public/locales
 
       - name: Check if the source and target branches are different
         if: ${{ github.event.pull_request.base.ref == github.event.pull_request.head.ref }}
@@ -80,6 +80,7 @@ jobs:
           echo "Source Branch ${{ github.event.pull_request.head.ref }}"
           echo "Target Branch ${{ github.event.pull_request.base.ref }}"
           echo "Error: Source and Target Branches are the same. Please ensure they are different."
+          echo "Error: Close this PR and try again."
           exit 1
 
   Check-Sensitive-Files:
@@ -92,16 +93,21 @@ jobs:
       
       - name: Get Changed Unauthorized files
         id: changed-unauth-files
-        uses: tj-actions/changed-files@v40
+        uses: tj-actions/changed-files@v45
         with:
           files: |
+            .env*
+            vitest.config.js
+            src/App.tsx
             .github/**
             env.example
             .node-version
             .husky/**
             scripts/**
+            src/style/** 
             schema.graphql
             package.json
+            package-lock.json
             tsconfig.json
             .gitignore
             .eslintrc.json
@@ -123,6 +129,17 @@ jobs:
             ISSUE_GUIDELINES.md
             PR_GUIDELINES.md
             README.md
+            *.pem
+            *.key
+            *.cert
+            *.password
+            *.secret
+            *.credentials
+            .nojekyll
+            yarn.lock
+            docs/docusaurus.config.ts
+            docs/sidebar*
+            CNAME
             
       - name: List all changed unauthorized files
         if: steps.changed-unauth-files.outputs.any_changed == 'true' || steps.changed-unauth-files.outputs.any_deleted == 'true'
@@ -132,6 +149,7 @@ jobs:
           for file in ${CHANGED_UNAUTH_FILES}; do
             echo "$file is unauthorized to change/delete"
           done
+          echo "To override this, apply the 'ignore-sensitive-files-pr' label"          
           exit 1
 
   Count-Changed-Files:
@@ -144,7 +162,7 @@ jobs:
 
       - name: Get changed files
         id: changed-files
-        uses: tj-actions/changed-files@v40
+        uses: tj-actions/changed-files@v45
 
       - name: Echo number of changed files
         env: 
@@ -170,6 +188,10 @@ jobs:
       - name: Checkout code
         uses: actions/checkout@v4
 
+      - name: Get changed files
+        id: changed-files
+        uses: tj-actions/changed-files@v45
+
       - name: Set up Python
         uses: actions/setup-python@v5
         with:
@@ -177,12 +199,32 @@ jobs:
 
       - name: Run Python script
         run: |
-          python .github/workflows/eslint_disable_check.py
+          python .github/workflows/scripts/eslint_disable_check.py --files ${{ steps.changed-files.outputs.all_changed_files }}
+
+  Check-Code-Coverage-Disable:
+    name: Check for code coverage disable
+    runs-on: ubuntu-latest
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v4
+
+      - name: Get changed files
+        id: changed-files
+        uses: tj-actions/changed-files@v45
+
+      - name: Set up Python
+        uses: actions/setup-python@v5
+        with:
+          python-version: 3.9
+
+      - name: Run Python script
+        run: |
+          python .github/workflows/scripts/code_coverage_disable_check.py --files ${{ steps.changed-files.outputs.all_changed_files }} 
 
   Test-Application:
     name: Test Application
     runs-on: ubuntu-latest
-    needs: [Code-Quality-Checks, Check-ESlint-Disable]
+    needs: [Code-Quality-Checks, Check-ESlint-Disable,Check-Code-Coverage-Disable]
     steps:
       - name: Checkout the Repository
         uses: actions/checkout@v4
@@ -197,11 +239,30 @@ jobs:
       
       - name: Get changed TypeScript files
         id: changed-files
-        uses: tj-actions/changed-files@v40
+        uses: tj-actions/changed-files@v45
           
-      - name: Run tests
+      - name: Run Jest Tests
         if: steps.changed-files.outputs.only_changed != 'true'
-        run: npm run test -- --watchAll=false --coverage       
+        env:
+          NODE_V8_COVERAGE: './coverage/jest'
+        run: |
+          npm run test -- --watchAll=false --coverage
+
+      - name: Run Vitest Tests
+        if: steps.changed-files.outputs.only_changed != 'true'
+        env:
+          NODE_V8_COVERAGE: './coverage/vitest'
+        run: |
+          npm run test:vitest:coverage
+
+      - name: Merge Coverage Reports
+        if: steps.changed-files.outputs.only_changed != 'true'
+        run: |
+          mkdir -p coverage
+          if ! npx lcov-result-merger 'coverage/*/lcov.info' > 'coverage/lcov.info'; then
+            echo "Failed to merge coverage reports"
+            exit 1
+          fi     
       
       - name: TypeScript compilation for changed files
         run: |
@@ -210,25 +271,56 @@ jobs:
               npx tsc --noEmit "$file"
             fi
           done
-        
+
       - name: Present and Upload coverage to Codecov as ${{env.CODECOV_UNIQUE_NAME}}
         uses: codecov/codecov-action@v4
         with:
           token: ${{ secrets.CODECOV_TOKEN }}
           verbose: true
+          gcov_ignore: 'docs/'
           fail_ci_if_error: false
+          files: './coverage/lcov.info'
           name: '${{env.CODECOV_UNIQUE_NAME}}'
 
       - name: Test acceptable level of code coverage
-        uses: VeryGoodOpenSource/very_good_coverage@v2
+        uses: VeryGoodOpenSource/very_good_coverage@v3
         with:
           path: "./coverage/lcov.info"
-          min_coverage: 95.0
+          min_coverage: 0.0
 
-  Graphql-Inspector:
-    if: ${{ github.actor != 'dependabot[bot]' }}
-    name: Runs Introspection on the GitHub talawa-api repo on the schema.graphql file
+  # Graphql-Inspector:
+  #   if: ${{ github.actor != 'dependabot[bot]' }}
+  #   name: Runs Introspection on the GitHub talawa-api repo on the schema.graphql file
+  #   runs-on: ubuntu-latest
+  #   steps:
+  #     - name: Checkout the Repository
+  #       uses: actions/checkout@v4
+
+  #     - name: Set up Node.js
+  #       uses: actions/setup-node@v4
+  #       with:
+  #         node-version: '22.x'
+
+  #     - name: resolve dependency
+  #       run: npm install -g @graphql-inspector/cli
+      
+  #     - name: Clone API Repository
+  #       run: |
+  #         # Retrieve the complete branch name directly from the GitHub context
+  #         FULL_BRANCH_NAME=${{ github.base_ref }}
+  #         echo "FULL_Branch_NAME: $FULL_BRANCH_NAME"
+          
+  #         # Clone the specified repository using the extracted branch name
+  #         git clone --branch $FULL_BRANCH_NAME https://github.com/PalisadoesFoundation/talawa-api && ls -a 
+
+  #     - name: Validate Documents
+  #       run: graphql-inspector validate './src/GraphQl/**/*.ts' './talawa-api/schema.graphql'
+        
+  Start-App-Without-Docker:
+    name: Check if Talawa Admin app starts (No Docker)
     runs-on: ubuntu-latest
+    needs: [Code-Quality-Checks, Test-Application]
+    if: github.actor != 'dependabot'
     steps:
       - name: Checkout the Repository
         uses: actions/checkout@v4
@@ -236,22 +328,98 @@ jobs:
       - name: Set up Node.js
         uses: actions/setup-node@v4
         with:
-          node-version: '22.x'
+          node-version: '20.x'
 
-      - name: resolve dependency
-        run: npm install -g @graphql-inspector/cli
-      
-      - name: Clone API Repository
+      - name: Install Dependencies
+        run: npm install
+
+      - name: Build Production App
+        run: npm run build
+
+      - name: Start Production App
         run: |
-          # Retrieve the complete branch name directly from the GitHub context
-          FULL_BRANCH_NAME=${{ github.base_ref }}
-          echo "FULL_Branch_NAME: $FULL_BRANCH_NAME"
-          
-          # Clone the specified repository using the extracted branch name
-          git clone --branch $FULL_BRANCH_NAME https://github.com/PalisadoesFoundation/talawa-api && ls -a 
+          npm run preview &
+          echo $! > .pidfile_prod
+      - name: Check if Production App is running
+        run: |
+          chmod +x .github/workflows/scripts/app_health_check.sh
+          .github/workflows/scripts/app_health_check.sh 4173 120
+      - name: Stop Production App
+        run: |
+          if [ -f .pidfile_prod ]; then
+            kill "$(cat .pidfile_prod)"
+          fi
+      - name: Start Development App
+        run: |
+          npm run serve &
+          echo $! > .pidfile_dev
+      - name: Check if Development App is running
+        run: |
+          chmod +x .github/workflows/scripts/app_health_check.sh
+          .github/workflows/scripts/app_health_check.sh 4321 120
+      - name: Stop Development App
+        if: always()
+        run: |
+          if [ -f .pidfile_dev ]; then
+            kill "$(cat .pidfile_dev)"
+          fi
 
-      - name: Validate Documents
-        run: graphql-inspector validate './src/GraphQl/**/*.ts' './talawa-api/schema.graphql'
+  Docker-Start-Check:
+    name: Check if Talawa Admin app starts in Docker
+    runs-on: ubuntu-latest
+    needs: [Code-Quality-Checks, Test-Application]
+    if: github.actor != 'dependabot'
+    steps:
+      - name: Checkout the Repository
+        uses: actions/checkout@v4
+
+      - name: Set up Docker
+        uses: docker/setup-buildx-action@v3
+        with:
+          driver-opts: |
+            image=moby/buildkit:latest
+      - name: Build Docker image
+        run: |
+          set -e
+          echo "Building Docker image..."
+          docker build -t talawa-admin-app .
+          echo "Docker image built successfully"
+      - name: Run Docker Container
+        run: |
+          set -e
+          echo "Started Docker container..."
+          docker run -d --name talawa-admin-app-container -p 4321:4321 talawa-admin-app
+          echo "Docker container started successfully"
+      - name: Check if Talawa Admin App is running
+        run: |
+          chmod +x .github/workflows/scripts/app_health_check.sh
+          .github/workflows/scripts/app_health_check.sh 4321 120 true
+      - name: Stop Docker Container
+        if: always()
+        run: |
+          docker stop talawa-admin-app-container
+          docker rm talawa-admin-app-container
+
+  Test-Docusaurus-Deployment:
+    name: Test Deployment to https://docs-admin.talawa.io
+    runs-on: ubuntu-latest
+    needs: [Docker-Start-Check, Start-App-Without-Docker]
+    # Run only if the develop-postgres branch and not dependabot    
+    if: ${{ github.actor != 'dependabot[bot]' && github.event.pull_request.base.ref == 'develop-postgres' }}
+    steps:
+      - uses: actions/checkout@v4
+      - uses: actions/setup-node@v4
+        with:
+          node-version: 22
+          cache: yarn
+          cache-dependency-path: 'docs/'
+      # Run Docusaurus in the ./docs directory
+      - name: Install dependencies
+        working-directory: ./docs
+        run: yarn install --frozen-lockfile
+      - name: Test building the website
+        working-directory: ./docs
+        run: yarn build
 
   Check-Target-Branch:
     if: ${{ github.actor != 'dependabot[bot]' }}
@@ -259,7 +427,25 @@ jobs:
     runs-on: ubuntu-latest
     steps:
       - name: Check if the target branch is develop
-        if: github.event.pull_request.base.ref != 'develop'
+        if: github.event.pull_request.base.ref != 'develop-postgres'
         run: |
-          echo "Error: Pull request target branch must be 'develop'. Please refer PR_GUIDELINES.md"
+          echo "Error: Pull request target branch must be 'develop-postgres'. Please refer PR_GUIDELINES.md"
+          echo "Error: Close this PR and try again."
           exit 1
+
+  Validate-Coderabbit:
+    name: Validate CodeRabbit Approval
+    runs-on: ubuntu-latest
+    if: github.actor != 'dependabot[bot]'
+    needs: [Test-Docusaurus-Deployment]
+    steps:
+      - name: Checkout Repository
+        uses: actions/checkout@v4
+      - name: Validate CodeRabbit.ai Approval
+        run: |
+          chmod +x $GITHUB_WORKSPACE/.github/workflows/scripts/validate-coderabbit.sh
+          $GITHUB_WORKSPACE/.github/workflows/scripts/validate-coderabbit.sh
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+          PR_NUMBER: ${{ github.event.pull_request.number }}
+          GITHUB_REPOSITORY: ${{ github.repository }}
